/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteRouteImport } from './routes/services.route'
import { Route as ProjectsRouteRouteImport } from './routes/projects.route'
import { Route as ProductsRouteRouteImport } from './routes/products.route'
import { Route as AboutRouteRouteImport } from './routes/about.route'
import { Route as IndexRouteRouteImport } from './routes/index.route'

const ServicesRouteRoute = ServicesRouteRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRouteRoute = ProjectsRouteRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRouteRoute = ProductsRouteRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRouteRoute = AboutRouteRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRouteRoute = IndexRouteRouteImport.update({
  id: '/',
  path: '',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/about': typeof AboutRouteRoute
  '/products': typeof ProductsRouteRoute
  '/projects': typeof ProjectsRouteRoute
  '/services': typeof ServicesRouteRoute
}
export interface FileRoutesByTo {
  '/about': typeof AboutRouteRoute
  '/products': typeof ProductsRouteRoute
  '/projects': typeof ProjectsRouteRoute
  '/services': typeof ServicesRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRouteRoute
  '/about': typeof AboutRouteRoute
  '/products': typeof ProductsRouteRoute
  '/projects': typeof ProjectsRouteRoute
  '/services': typeof ServicesRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/about' | '/products' | '/projects' | '/services'
  fileRoutesByTo: FileRoutesByTo
  to: '/about' | '/products' | '/projects' | '/services'
  id: '__root__' | '/' | '/about' | '/products' | '/projects' | '/services'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRouteRoute: typeof IndexRouteRoute
  AboutRouteRoute: typeof AboutRouteRoute
  ProductsRouteRoute: typeof ProductsRouteRoute
  ProjectsRouteRoute: typeof ProjectsRouteRoute
  ServicesRouteRoute: typeof ServicesRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof IndexRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRouteRoute: IndexRouteRoute,
  AboutRouteRoute: AboutRouteRoute,
  ProductsRouteRoute: ProductsRouteRoute,
  ProjectsRouteRoute: ProjectsRouteRoute,
  ServicesRouteRoute: ServicesRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
